### ISSUE TITLE
Recursion on lists is broken?

### ISSUE THREAD

**Issue by Crazycolorz5** [hazelgrove/hazel#1029]
It seems that reconstructions on stack are somehow lost? See the screenshot, this is done on `dev`.

![image](https://github.com/hazelgrove/hazel/assets/1497003/d7004ac3-4261-47c9-9364-66991f105692)

**Comment by cyrus-** [comment]
List items are separated by commas, not semicolons -- semicolon is sequencing, so `1; 2; 3` evaluates to `3`.
