### ISSUE TITLE
Hazel as UI for new language ?

### ISSUE THREAD

**Issue by zeroexcuses** [hazelgrove/hazel#1034]
Is it easy to use Hazel as a UI for a new language? I.e. if there something like Context-Free-Grammar, Backus Normal Form, Parsing Expression Grammar, ... or something else where:

(1) we specify the syntax of the language in this format
(2) we can then use Hazel as a structural editor for the new language ?

If not, how easy/hard is it to use Hazel for a new language ?

Thanks!

**Comment by cyrus-** [comment]
We're working on that (keep an eye on http://tylr.fun) but not ready yet
