### ISSUE TITLE
Proposal to clarify naming around co-ctx/free

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/hazel#1036]
Currently the co_ctx instance in cursorinfo is called 'free', which is sub-optimal as it can be misleading (my bad). I propose (as a separate PR from #1033 for git clarity) that we just rename 'free' to 'co_ctx' everywhere. Then, we can use the following vocabulary to make precise the notions of free/bound and used/unused:

- A locally free variable (in an expression) is one that occurs in the co_ctx of that expression
- A global free variable (in the program) is one that occurs in the co_ctx but not the ctx of _some_ expression
- A locally unused variable (in an expression) is one the occurs in the ctx but not the co-ctx of that expression
- A global unused variable (in the program) is one that occurs in the ctx but not the co_ctx of _some_ expression

theorems(?):
- to determine if a variable is globally free, it suffices to consider expressions which are variable references (locus of ctx lookups)
- to determine if a variable is globally unused, it suffices to consider expressions which are the bodies of binding forms (locus of ctx extensions)

@cyrus above is maybe a stilted way of looking at things but seems sort of interesting in a kind of galois connectiony kind of way?

**Comment by cyrus-** [comment]
this seems like a reasonable cleanup to me
