### ISSUE TITLE
Error when defining type alias in Google Chrome browser

### ISSUE THREAD

**Issue by gensofubi** [hazelgrove/hazel#1047]
In adt-defs-after branch, defining a type alias (on inputing `type `) causes the entire webpage to crash with the following error message:

"hazel.js:30466 Async_kernel: Unhandled exception (Failure "group not found: empty_hole_tpat_group")"

This happens on Google Chrome browser (version 114.0.5735.110, 64-bit, cohort: Stable).

**Comment by disconcision** [comment]
sounds like a langdocs issue. try resetting localstorage

**Comment by gensofubi** [comment]
yes that worked. Thanks!
