### ISSUE TITLE
Can't use logical or

### ISSUE THREAD

**Issue by gensofubi** [hazelgrove/hazel#1061]
I find there is `("logical_or", mk_infix("||", Exp, P.or_)),` in the forms, but can't use it in hazel. Instead it is recognized as rules.
![FP{$B8V}2T( `_}YQHU QON](https://github.com/hazelgrove/hazel/assets/71319371/ec70059c-ef99-437b-82b8-11282869eb76)
Expected output: true

**Comment by disconcision** [comment]
The current syntax engine doesn't support operators which share a prefix with existing delimiters (here || shares a prefix with the bar from case rules). In my branch I've renamed the or operator to "\\/" for the time being
