### ISSUE TITLE
be more selective about scroll-to-caret

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/hazel#1085]
Select-all doesn't scroll to caret in vscode and probably shouldn't here. Especially true if quadruple-click selects all, as there is a significant possibility of accidental quadclick and incumbent context loss

**Comment by Negabinary** [comment]
I've noticed there's more unwanted scroll-to-caret cases too, for example, if you click anywhere (e.g. on blank space in the language documentation panel) it will scroll to caret too.

**Comment by disconcision** [comment]
is this (@Negabinary's comment) a regression? not sure I noticed this before this semester

**Comment by cyrus-** [comment]
It may be, not sure. Could try one of the old builds from 490 last semester.
