### ISSUE TITLE
Certain multiply-annotated patterns lead to internal exceptions

### ISSUE THREAD

**Issue by pigumar1** [hazelgrove/hazel#1100]
![image](https://github.com/hazelgrove/hazel/assets/108375845/c061385c-3975-4ce0-9e49-fa864c7791ac)
![image](https://github.com/hazelgrove/hazel/assets/108375845/75f66983-4c35-4fd9-b120-eff99ae5b301)

Similarly, annotating both the variable bound to a function and the input variable of that function (which must be an `Unknown(Internal)`) results in a CastBVHoleGround exception:
![image](https://github.com/hazelgrove/hazel/assets/108375845/3b827d42-7e73-4d58-86d7-0a7cb70b0500)
In most cases, users won't go into this. However, if a user annotates a function that takes a function as an input, and then attempts to annotate the variable type of that function, they may encounter this issue (still not likely).

**Comment by cyrus-** [comment]
Closing in favor of #1233
