### ISSUE TITLE
Persist unbound type variables into Typ.t and show

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#1150]
![image](https://github.com/hazelgrove/hazel/assets/280638/98a88fa2-46b5-490b-95ee-18188704a7f2)

In the above, the cursor inspector should show "T" with a hole around it, rather than just `?`.

**Comment by disconcision** [comment]
@cyrus- There is already infrastructure around this, though it is only exposed on-hover:

<img width="903" alt="Screenshot 2023-12-04 235253" src="https://github.com/hazelgrove/hazel/assets/22436459/89b8fc77-7d6c-4a2b-9fe4-42d934ea8fe7">

It doesn't work for the case you show though, the type just shows as provenance: Internal. Not sure if this is just an oversight or if there's some delicate type provenance logic around casting here... something to be on the lookout for though
