### ISSUE TITLE
Fix integers in patterns

### ISSUE THREAD

**Issue by Negabinary** [hazelgrove/hazel#1157]
In dev, `let 1 = 2 in 1` doesn't error but also doesn't evaluate.

![image](https://github.com/hazelgrove/hazel/assets/31668468/4d6da862-338b-4ad1-a275-adc010f8d949)

**Comment by disconcision** [comment]
this is consistent with the current match behavior (becomes stuck on fallthrough). we should probably give more specific feedback to both. there is currently a feature branch which gives stack warnings in such cases (refutable let patterns), but i think we decided to put that off until the general case is in (exhaustiveness checking for match).

in general i think we need to think more carefully about the UX of stuck lets... for example, lets with incomplete patterns. these can often clutter up the value display even when they are irrelevant to the final value. some at least view-level intervention might be called for.

in this case, if we wanted to surface the (runtime) reason the definition is stuck in the view, we would need to decide what to put the error on... not totally obvious to me how to depict this clearly

**Comment by cyrus-** [comment]
closing as this is a specific instance of more general issue of no good feedback on match failure
