### ISSUE TITLE
Inductive definitions of typing and action rules and statement of theorems in Coq

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#12]
We should give an inductive language definition and at least state the metatheorems and the theorems relating the functional implementation to the inductive definition. We can prove them later once the language design stabilizes.

**Comment by dmoon1221** [comment]
No longer using Coq as of https://github.com/hazelgrove/hazel/commit/bb3a0f862622c74f559472ddcc7c2d5ec85b3d8b
