### ISSUE TITLE
NonEmptyHole Decoration prevents clicks

### ISSUE THREAD

**Issue by Negabinary** [hazelgrove/hazel#1201]
In the screenshot below, you can't click on the green box because it is under the error decoration's hitbox.

![image](https://github.com/hazelgrove/hazel/assets/31668468/3b1ad54a-d375-4d3c-a392-a447244083b0)

@disconcision also of interest: it turns out the two boxes are coming from the fact that the free variable gets elaborated to `NonEmptyHole(_, _, _, FreeVar(_))`

**Comment by disconcision** [comment]
> free variable gets elaborated to NonEmptyHole(_, _, _, FreeVar(_))
amazing, did I do that
