### ISSUE TITLE
restore equivalence symbol font

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#1210]
on previous `dev`:
<img width="30" alt="image" src="https://github.com/hazelgrove/hazel/assets/280638/36c974a8-be46-4d77-a99f-f0d8e6b0b0a2"> 
vs on current `dev`:
<img width="32" alt="image" src="https://github.com/hazelgrove/hazel/assets/280638/ca616667-7803-44a8-a3ae-ae345bce21be">

**Comment by disconcision** [comment]
are you seeing this locally? on the build server i see:

<img width="71" alt="Screenshot 2024-02-11 001804" src="https://github.com/hazelgrove/hazel/assets/22436459/dcd837f2-ceba-4c74-98f3-9292d0b1cf9e">

**Comment by cyrus-** [comment]
hm yeah seems to only be an issue locally + when I have the stepper on. on the build server the equivalences don't align the same when the stepper is on and off but the icon seems to stay the same. weird...
