### ISSUE TITLE
arrow types should be right associative

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#1215]
![image](https://github.com/hazelgrove/hazel/assets/280638/db3f9318-cad1-4c89-9f67-a2d2ce6a2688)

**Comment by disconcision** [comment]
wat. is this a regression?

**Comment by cyrus-** [comment]
not sure when this first showed up, but it was present in 490 A1 this semester at least

**Comment by cyrus-** [comment]
fixed by #1342
