### ISSUE TITLE
List literal function argument ExplainThis throws an error

### ISSUE THREAD

**Issue by Negabinary** [hazelgrove/hazel#1236]
![image](https://github.com/hazelgrove/hazel/assets/31668468/4104851d-2058-4c7f-9396-2b2dba213b4f)

**Comment by cyrus-** [comment]
@disconcision can you take a look

**Comment by disconcision** [comment]
Looks like formatting string and list literal in function pattern description are out of sync. Probably some similar lurking cases here for syntactic compositions that arent often used
