### ISSUE TITLE
evaluator hangs with uuid exception in console on this example

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#1238]
![image](https://github.com/hazelgrove/hazel/assets/280638/32af5627-e643-4fe0-bd62-1ff691f836b7)

(should end with a cast error)

**Comment by disconcision** [comment]
seems to work on build server dev:
<img width="1024" alt="Screenshot 2024-03-11 at 4 04 36 PM" src="https://github.com/hazelgrove/hazel/assets/22436459/37b0d0ce-af41-47a3-81dd-a197b3d676d4">
