### ISSUE TITLE
Evaluation finishes half way through this awkward cast example

### ISSUE THREAD

**Issue by Negabinary** [hazelgrove/hazel#1240]
![image](https://github.com/hazelgrove/hazel/assets/31668468/dcbf7221-a08f-4424-8a1e-edc631a8c634)

`(fun (x,y) :(Int,  ) -> x+1)((fun x -> x)(3.2,  ))`

**Comment by Negabinary** [comment]
so the issue is there's a closure getting in the way of the cast calculus doing its thing.

Closure(e<Ground=>Hole>)<Hole=>Ground>

I'll fix it but it's going to break hole closures, which we're not using for now, but @cyrus- we should have a chat at some point about what hole closures are useful for, so I can think about how to bring them back later.

**Comment by cyrus-** [comment]
@Negabinary okay, can you add this as an agenda item for our next meeting.
