### ISSUE TITLE
`+ X(Int)` should not be a ground type

### ISSUE THREAD

**Issue by Negabinary** [hazelgrove/hazel#1260]
Breaking example on dev:
![image](https://github.com/hazelgrove/hazel/assets/31668468/0d40c01b-ca2f-42e3-90d8-a5367b092ecd)

```
let x : + B( ) = B(1) in
let y : + B(Int) = x in
let B(n) = y in
n + 2
```

I think constructors should only be ground if all their arguments are hole type?

**Comment by Negabinary** [comment]
Once the ground type issue is fixed, there will also be a "Invalid_argument" issue here:
![image](https://github.com/hazelgrove/hazel/assets/31668468/d4f24a45-c241-401e-badb-c54826f50126)

```
let x : A + B([ ]) = B([2]) in
let y : A + B([Int]) = x in
let B(z): A + B([Int]) = y in
1::z
```

**Comment by Negabinary** [comment]
Also pattern matching stops if there is a cast that re-orders the constructors in a type

![image](https://github.com/hazelgrove/hazel/assets/31668468/3e710498-1455-4ce5-9982-004b38e7f0fc)

```
let x : + A + B( ) = B([2]) in
let y : + B([Int]) + A = x in
3::case y
  | A => []
  | B(x) => x
end
```

**Comment by disconcision** [comment]
ah... consistency normalizes ordering, but i guess post-elaboration we dont do consistency any more.
(i continue to feel anonymous sums are more trouble than theyre worth)
