### ISSUE TITLE
fix `>`

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#1275]
We accidentally broke the `>` operator...

<img width="618" alt="image" src="https://github.com/hazelgrove/hazel/assets/280638/7f8cf292-f244-46b7-8a3a-1d73e5009f1a">

**Comment by disconcision** [comment]
Probably the same bug, but posting just in case it's distinct. I brought a branch of mine (which makes changes to the zipper data type) current with dev, and when I tried to regenerate the Init.ml data, the examples ends up broken:
<img width="1093" alt="Screenshot 2024-04-22 at 5 27 30 PM" src="https://github.com/hazelgrove/hazel/assets/22436459/91638ccc-4322-4f85-8995-7a64c65fa4b0">

**Comment by cyrus-** [comment]
Yeah, same bug
