### ISSUE TITLE
Errors in Polymorphism and Basic Reference examples

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/hazel#1278]
On build server dev I'm seeing a variety of suspicious-looking errors on both these example sheets:
<img width="1029" alt="Screenshot 2024-04-22 at 5 20 34 PM" src="https://github.com/hazelgrove/hazel/assets/22436459/bd91a8f3-c572-47f7-9077-eb43345c14c9">

**Comment by cyrus-** [comment]
Thia is due to arrow associativity being broken
