### ISSUE TITLE
1 @ 2 doesn't throw an error

### ISSUE THREAD

**Issue by Negabinary** [hazelgrove/hazel#1298]
![image](https://github.com/hazelgrove/hazel/assets/31668468/d9b274e1-9def-47f9-a6aa-0b21a515672e)

`1 @ 2` should be a type error because 1 is not a list and `@` only takes lists

**Comment by disconcision** [comment]
Looks to have been introduced in a recent merge, likely polymorphism or a follow-up (not present in eg https://hazel.org/build/command_palette)

**Comment by Negabinary** [comment]
It could easily have been one of my list casting bug prs too
