### ISSUE TITLE
ListLit of different Construtor type does not raise type error

### ISSUE THREAD

**Issue by GuoDCZ** [hazelgrove/hazel#1313]
The following code should have a static error `Elements have inconsistent types: ... `in 5th line, but is mistakenly accepted in Hazel:
![image](https://github.com/hazelgrove/hazel/assets/113280601/50905b04-91d7-4ab4-9562-cd4d3109a5ee)
```haskell
type A = +A in
let a = A in
type B = +A in
let b = A in
[a, b]
```

**Comment by Negabinary** [comment]
I think this is actually intentional. You're right that this would be a bug in OCaml, where every sum type is treated as different, but in Hazel the `type` keyword is literally just an alias. In Hazel you can also write that code like:

```
let a : +A = A in
let b : +A = A in
[a,b]
```
