### ISSUE TITLE
evaluation bug involving cases

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/hazel#1345]
the tests on the ADT dynamics slide are now indet. i investigated it by inlining as shown in screenshot. interestingly if you do one more inlining  (of exp-equals) then evaluation dose complete
<img width="801" alt="Screenshot 2024-07-31 at 9 52 10 PM" src="https://github.com/user-attachments/assets/160c64cb-7a83-43cf-8f03-a31c68c0d98a">

**Comment by cyrus-** [comment]
@Negabinary could you look at this?
