### ISSUE TITLE
Large files to consider refactoring or breaking up (with line count) (use submodules and then include them):

### ISSUE THREAD

**Issue by adamsmd** [hazelgrove/hazel#149]
- 1268 src/hazelcore/semantics/ZExp.re
- 1788 src/hazelcore/semantics/CursorInfo.re
- 1824 src/hazelweb/gui/CursorIndicators.re
- 2046 src/hazelcore/semantics/CursorPath.re
- 2205 src/hazelcore/semantics/Dynamics.re
- 2216 src/hazelcore/semantics/Statics.re
- 3206 src/hazelweb/gui/Code.re
- 7071 src/hazelcore/semantics/Action.re

**Comment by cyrus-** [comment]
Working on this for all the ones that have Exp/Typ/Pat submodules. For the others, can you make issues for any that need further breaking down? Some of these might be intrinsically long.
