### ISSUE TITLE
decide about using Bucklescript

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#16]
before too much new UI code gets written, we should decide if we are going to use Bucklescript or js_of_ocaml. Discuss!

**Comment by MichaelHilton** [comment]
Bucklescript seems to be well documented with clean examples, and plays nice with JavaScript (i.e. You can call OCaml from JavaScript cleanly) I would say +1 for bucklescript.

**Comment by cyrus-** [comment]
Dunno how much we're going to need to interact with JS but yeah.

**Comment by MichaelHilton** [comment]
Yah. I'm not saying we should be doing that, but it's nice to have the option. Also, they do it by keeping the OCaml names, which I suspect might make it easier to debug...

**Comment by cyrus-** [comment]
yeah, debugging might be a bit easier, though we also haven't tried using the js_of_ocaml source map support

**Comment by cyrus-** [comment]
If we go with Bucklescript, this might be a useful reference https://blog.behrends.io/how-to-setup-reasonml-for-a-react-native-project-8c51f1cc1d34

**Comment by cyrus-** [comment]
now that I'm used to js_of_ocaml / Eliom's error messages, I rather like that it statically guarantees my HTML is well-formed, and that my DOM manipulation code makes sense. i also figured out more of how debugging works. this might be worth revisiting one day in the future when we're trying to optimize for performance, but for now I'm going to stick with what's been working well so far.
