### ISSUE TITLE
extra holes are added in multiple situations

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#246]
* inserting an infix operator between two expressions (but not patterns) separated by a space
* using an expanding keyword ("let", "case") before an expression, e.g. when pressing space at `let| 3`

**Comment by cyrus-** [comment]
similar issue arises pressing backspace in the following situation:
![Screenshot from 2020-05-24 22-42-04](https://user-images.githubusercontent.com/280638/82773367-d694de80-9e0f-11ea-8614-1619393437d8.png)

**Comment by cyrus-** [comment]
(also I don't think that's not how we want this to render, but I assume that will be addressed in next version of layout code?)

**Comment by dm0n3y** [comment]
Not sure what you mean about the last situation. If you delete the parentheses, the let line is placed on a separate line below `1 + ` so you need to generate a new empty hole.

**Comment by cyrus-** [comment]
ah I see. a little odd but I guess not much else you can do other than delete the whole let expression.
