### ISSUE TITLE
Incorrect error message on tuples

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#258]
it says "expecting an expression of type 1-tuple" but the type should be Int
![Screenshot from 2020-05-16 19-59-48](https://user-images.githubusercontent.com/280638/82132626-d9f4ee00-97af-11ea-9f00-99229a0be882.png)

**Comment by cdfa** [comment]
I can't reproduce on my machine (Manjaro Linux, Chrome). At the moment I don't get any error, as is reported in #269. The inverse case, where a tuple type is expected, but an Int is given, gives the correct error message though.

**Comment by cyrus-** [comment]
yeah this seems to be masked by #269 but I suspect the problem will still exist once that bug is fixed...

**Comment by cyrus-** [comment]
![Screenshot from 2020-05-24 20-36-23](https://user-images.githubusercontent.com/280638/82768646-4dc17700-9dfe-11ea-951e-c568f8371d62.png)
still happening when the tuple is parenthesized
