### ISSUE TITLE
tuple completion does not work inside an opseq

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#259]
e.g. pressing `(` in the following code does not cause tuple completion

![Screenshot from 2020-05-09 13-02-45](https://user-images.githubusercontent.com/280638/82132654-f8f38000-97af-11ea-925e-a2bcab22eeab.png)

**Comment by cdfa** [comment]
I can't reproduce on my machine (Manjaro Linux, Chrome). Could you track down where the issue is coming from?

**Comment by dm0n3y** [comment]
Fixed by https://github.com/hazelgrove/hazel/commit/770416966732cfe0f1b029ab01e8efdd1445e022
