### ISSUE TITLE
Different Zipper behavior for Plus/Minus Op and Times Op

### ISSUE THREAD

**Issue by Yunif3** [hazelgrove/hazel#264]
Plus and Minus operators allow you to right-arrow into the operator while Times operator require you to backspace from the second argument in order to edit the operator.
Also, the spacing is different in the two cases.

![image](https://user-images.githubusercontent.com/43325126/82383346-968ebf80-99fb-11ea-9be2-f74f17fc97ad.png)

![image](https://user-images.githubusercontent.com/43325126/82383457-d3f34d00-99fb-11ea-8b45-d3e6537cc34e.png)

**Comment by dm0n3y** [comment]
A couple possible ways to fix:
- add padding around `*` in `UHDoc.re`, which will give them distinct cursor positions
- distinguish `SChar` actions that are allowed in text leaves vs operators, use this check to automatically move the cursor before performing an `SChar` action for operators at the end of an operand (we do something similar already when performing a `Construct` action when the cursor is an operator or delimiter)

**Comment by Yunif3** [comment]
Thank you for the suggestion @dmoon1221.
I was actually able to solve it by fixing `inline_padding_of_operator` in `UHDoc.re` but didn't close the issue yet so that I can close it with the next PR.

**Comment by cyrus-** [comment]
yeah let's just put space around `*`
