### ISSUE TITLE
Cannot edit parentheses in analytic position

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#277]
If I try to type `x` or `1` here, it doesn't work with a "[Program.InvalidInput" error in the console. It works if I enter an unbound variable like `y`.

![Screenshot from 2020-05-23 21-02-10](https://user-images.githubusercontent.com/280638/82743384-ae867c00-9d38-11ea-9347-304e9d64210d.png)

**Comment by dm0n3y** [comment]
Can't repro this either. How are you distinguishing between `x` vs `y`?

**Comment by cyrus-** [comment]
oops sorry I had bound x after taking the screenshot to test that

**Comment by dm0n3y** [comment]
Hadn't pulled latest commits on `dev`. Bug appeared upon merging https://github.com/hazelgrove/hazel/pull/215. cc @hannahpotter
