### ISSUE TITLE
Cannot delete let binding in any nested context

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#278]
![Screenshot from 2020-05-23 21-04-30](https://user-images.githubusercontent.com/280638/82743412-06bd7e00-9d39-11ea-8beb-4b239685e4ae.png)

Pressing backspace here causes a Failure exception. Works for case.

**Comment by dm0n3y** [comment]
Issue here is that the nested block becomes an empty line followed by a hole, and the leading empty line gets interpreted as a user newline when generating new layout, so there's no caret position generated for it. Getting a caret position to generate for the user newline position is not as simple as it sounds given current implementation assumptions. Will give this another go another day.

**Comment by disconcision** [comment]
Just affirming that this effects a let binding nested in anything, not just another let:
<img width="1299" alt="Screen Shot 2021-06-27 at 1 07 34 PM" src="https://user-images.githubusercontent.com/22436459/123553396-f1d7c900-d748-11eb-874c-5cee6a4a8f8d.png">
