### ISSUE TITLE
Cannot apply functions

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#279]
I can't press space here!
![Screenshot from 2020-05-23 21-43-35](https://user-images.githubusercontent.com/280638/82743822-826df980-9d3e-11ea-8675-162d7d57c046.png)

**Comment by dm0n3y** [comment]
I can't repro. @cyrus- can you?

**Comment by cyrus-** [comment]
still happening for me on fresh dev build on Chromium...

**Comment by dm0n3y** [comment]
Hadn't pulled latest commits on `dev`. Bug appeared upon merging https://github.com/hazelgrove/hazel/pull/215. I'm guessing it's the same underlying issue as https://github.com/hazelgrove/hazel/issues/277 since both throw `InvalidInput` errors. cc @hannahpotter
