### ISSUE TITLE
Hard-coded left injection

### ISSUE THREAD

**Issue by matthewhammer** [hazelgrove/hazel#28]
https://github.com/hazelgrove/hazel/blob/a04ae650aa5f0a7399091a0f03b296c9469fb9c2/src/semantics.v#L802

Seems like there's a bug where injection construction always creates a Left injection, even when the user asks for a right injection.

**Comment by cyrus-** [comment]
Don't think this is broken? The "side" variable determines which injection
it is. The "LeftSum" is the Z-expression direction, not the side of the
injection.

**Comment by matthewhammer** [comment]
Yeah, I just realized that's the wrong line (the line I quoted is fine), but there is an issue elsewhere.  It's just more subtle than that.

To recreate the issue:
 - Create a right injection
 - Fill the value of the injection to be a number constant
 - The injection will be rewritten to be a left injection
