### ISSUE TITLE
transition from Reason 2 to Reason 3

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#29]
some major syntactic changes so we should do this soon.

there is some automatic way to do this conversion.

**Comment by cyrus-** [comment]
the more I look at Reason 3, the less I like it. I mean apparently you are supposed to call functions of type a -> b -> c like f(x, y) because that looks more like JavaScript nevermind that it makes no sense given that tuples are also in the language.

barring a strong argument, I might eventually just transition back to basic OCaml syntax for the implementation.

**Comment by matthewhammer** [comment]
Such offenses are not trivial.  Your decision to switch back to OCaml syntax seems good to me.
