### ISSUE TITLE
cannot enter a sum type

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#295]
should be able to use `|` for sum types, but it doesn't work

**Comment by wlitwin** [comment]
It appears the issue is the action that gets triggered when you press `|` in a type context is: `(Construct (SOp SOr))` instead of `(Construct (SOp SVBar))` so when Action_Typ.re `perform_opseq` gets to this case:
```
  | (Construct(SOp(os)), ZOperand(CursorT(_) as zoperand, surround)) =>
    switch (operator_of_shape(os)) {
    | None => Failed
    | Some(op) => Succeeded(construct_operator(op, zoperand, surround))
  }
```
`operator_of_shape` fails because `SOr` is not one of the expected shapes.

**Comment by wlitwin** [comment]
It appears that `Cell.re` always maps `VBar` to `Construct(SOp(Or))`. It's unclear whether `Cell.re` should be changed to account for the context, or if `Action_Typ.re` should use `SOr => Some(Sum)` instead of `SVBar`. But either case seems like a fairly easy fix to make.
