### ISSUE TITLE
Hole numbering is resetting in perform_rules

### ISSUE THREAD

**Issue by cdfa** [hazelgrove/hazel#307]
![Screen Shot 2020-06-03 at 23 41 08](https://user-images.githubusercontent.com/8250462/83692293-fe482b80-a5f3-11ea-9c76-770fd6876977.png)

I think this is specific to the `perform_rules` level, but not 100% sure.

**Comment by cdfa** [comment]
I just discovered this has more to do with there being a `[]` as scrutinee than `perform_rules`. It is also older than, I thought. It was already present before the case-analysis-in-synthetic-position merge.

**Comment by cyrus-** [comment]
it seems to happen with any complete scrutinee, and seems only to happen in synthetic position, so might be related to @hannahpotter's refactoring of case?

**Comment by cyrus-** [comment]
also happens in expressions
![Screenshot from 2020-06-07 13-49-50](https://user-images.githubusercontent.com/280638/83976086-c415ad00-a8c5-11ea-9ca6-4440225a3659.png)

**Comment by cyrus-** [comment]
ahh the issue is actually with the code that @utkmehta recently added to reset hole numbering. the is_complete_operand function doesn't recurse into the rules. @utkmehta, can you take a look?
