### ISSUE TITLE
add swap support to undo history and action panel

### ISSUE THREAD

**Issue by dm0n3y** [hazelgrove/hazel#311]
https://github.com/hazelgrove/hazel/blob/49c621972371797e80d2777611b972893483726c/src/hazelweb/model/UndoHistory.re#L819

**Comment by cyrus-** [comment]
(SwapUp and SwapDown swap lines up and down, SwapLeft and SwapRight swap operands left and right)

**Comment by Yuning30** [comment]
OK, I'm working on this to support swap actions.
