### ISSUE TITLE
scrollbar showing on left of action panel

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#312]
![Screenshot from 2020-06-07 13-15-15](https://user-images.githubusercontent.com/280638/83975258-fb358f80-a8c0-11ea-887e-cc689ad824b8.png)

![Screenshot from 2020-06-07 13-14-47](https://user-images.githubusercontent.com/280638/83975260-fe308000-a8c0-11ea-9508-48388004119f.png)

**Comment by wlitwin** [comment]
Which browser and platform is this happening on? I can't get it to repro on Firefox 76 and Chromium 83 on Linux.

**Comment by cyrus-** [comment]
it's happening for me on Chromium 83.0.4103.97 on Arch Linux, but not on Firefox

**Comment by wlitwin** [comment]
hrm. I'll see if I can repo, my chromium is slightly behind:

Chromium | 83.0.4103.61 (Developer Build) (64-bit)
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}

**Comment by cyrus-** [comment]
problem persists when I go incognito and I don't think I have any settings messing with the page, so the discrepancy is strange...

**Comment by cyrus-** [comment]
it goes away if you add overflow: hidden to #collapsible-left-bar

**Comment by wlitwin** [comment]
That seems like a reasonable enough fix to me. The side bar contents should manage the scroll. Hiding it on the parent shouldn't cause any issue. I know scrollbars in general tend to be a bit finicky in browsers, this will at least make it explicit. I'll put up a change shortly.
