### ISSUE TITLE
cursor positioning on opseqs is incorrect

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#313]
![Screenshot from 2020-06-07 13-19-29](https://user-images.githubusercontent.com/280638/83975363-8dd62e80-a8c1-11ea-9655-dfed5ec98a1a.png)

this is on Linux -- seems like something may be off with the latest font metrics changes?

**Comment by hannahpotter** [comment]
Is it on Firefox and Chrome, or just Firefox? And does it work correctly if you zoom in and then out again?

**Comment by cyrus-** [comment]
both, and zooming doesn't seem to affect it...

**Comment by cyrus-** [comment]
seems to only happen when there are holes... works fine when there are literals in each position

**Comment by hannahpotter** [comment]
Does it work if the hole numbers are only a single digit (does it only get off after a hole that has a number that is 2 or more digits)? If so what is the left and right padding and width of the span.HoleLabel elements with a single vs two digit hole number? 
![InkedScreenshot (198)_LI](https://user-images.githubusercontent.com/21255175/84083449-dd3e5c80-a99e-11ea-9e63-29d14d5aaf2d.jpg)
