### ISSUE TITLE
Hole fixing not operating correctly with opseqs

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#340]
For example, if I type

`3.14 +.`, the `3.14` still has a hole around it. it is only fixed if I go an edit the literal itself.

This seems to be a problem beyond dotted operators, e.g.

```
let f : Int -> Int = _ in 
f +| 3
```

If I press backspace here, the hole around f does not disappear.

This is a fundamental correctness problem, so it should be high priority.

**Comment by dm0n3y** [comment]
Fixed via reverting buggy optimization https://github.com/hazelgrove/hazel/commit/9d809c9c41a2d3043a0374eb52955c7e4af4e1ee
