### ISSUE TITLE
infix exponentiation operator

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#364]
creating an issue for the future

Issues:
- We are currently using `^` for string concatenation, so we would need something else, e.g. `**` like Python, or use something else for string concatenation, like `++`.
- This complicates unary negation, unless we are ok with `-x**2` parsing as `(-x)**2` rather than `-(x**2)`. This could be resolved either with some special cases in the associate code, or by refactoring Seq to support unary ops natively (at the cost of complexity).

For these reasons, we might even choose not to implement infix exponentiation and stick to a `pow` function. For most use cases this is fine, though if we want to push Hazel into scientific computing where exponentiation is common, this may be a small usability issue.

**Comment by claban3** [comment]
I was wondering about adding unary operator support when I was writing the opp. I could look into this after resolving my PR, and alongside adding test infrastructure.

**Comment by cyrus-** [comment]
@claban3 don't worry about it for now, I think its better to start with unary ops being operands (and therefore binding more tightly than any binary ops). @anandrav is working on that. we can revisit this in the future, but I don't want to add a bunch of complexity to what we have for the sake of negative exponents before the code is stable.

**Comment by cyrus-** [comment]
another option is to lay out exponentiation as a superscript. main issue with that has to do with layout:

- if we allow arbitrary expressions in the superscript, what to do with complex expressions that take up space, e.g. let, case, nested exponentiation. we could restrict to simple operands like number literals, variables, maybe parenthesized opseqs
- the layout optimizer right now uses character counts as a proxy for width due to monospace font usage. smaller exponent font would mess that up. we could resolve this by padding the exponent to the nearest character width.

**Comment by claban3** [comment]
Ok
