### ISSUE TITLE
improve handling of line breaks and indentation in pretty printer

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#37]
Reason uses this library, might be something we can draw from this (probably can't use it directly because we need to generate HTML and some stuff on the side):

https://mjambon.github.io/mjambon2016/easy-format.html

**Comment by cyrus-** [comment]
a talk that I haven't watched yet on Reason's pretty printer: https://www.youtube.com/watch?v=jzJVhYesJUc&feature=youtu.be

**Comment by cyrus-** [comment]
and a paper on pretty printing by David Christiansen, David Darais and Weixi Ma that talks about proportional fonts and other interesting stuff: http://david.darais.com/assets/papers/final-pretty-printer/fpp.pdf

**Comment by nickcollins** [comment]
the concrete syntax should probably use reason's pretty printer as well - the ocaml pretty printer does the weird box thing, and maybe this other pretty printer understands unicode

**Comment by nickcollins** [comment]
i'll probably take a stab at it later
