### ISSUE TITLE
Crashes on latter "Just a Hole" example choice

### ISSUE THREAD

**Issue by nj-wilson** [hazelgrove/hazel#397]
`Async_kernel: Unhandled exception (Invalid_argument "option is None")`

Multiple example ways to reproduce:

1) From a fresh start, type anything into the empty hole, such as `1`.
    Choose any example from the drop-down besides "Just a Hole"
    Then choose "Just a Hole" from the drop-down.

2) From a fresh start, choose an example with a hole, like map
    Type anything into the hole at the bottom, such as `1`.
    Then choose "Just a Hole" from the drop-down.

**Comment by disconcision** [comment]
Closed by #513

**Comment by disconcision** [comment]
The crash is coming from the Option.get in get_selected_hole_instance. I don't exactly understand what selected_instances are, but it looks like they should probably be scoped to programs/cards/whatever, not global?

**Comment by cyrus-** [comment]
I believe the selected instance is the hole instance from the result being shown in the sidebar -- yes, that should not be global and can be invalidated by edits, so should probably be saved in the undo history too
