### ISSUE TITLE
minimal parenthesization

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#4]
We want to put parenthesis into the pretty printed output only where it is necessary to avoid ambiguity, rather than everywhere.

I have some intuitions about how this would work, but is there an established algorithm for this?

**Comment by ivoysey** [comment]
I'm more than 50% sure this is a classic dynamic programming question for
undergrads.


---Ian

**Comment by cyrus-** [comment]
it certainly felt like a homework assignment
