### ISSUE TITLE
Not able to create tuple object in annotated let statment

### ISSUE THREAD

**Issue by ecdeuts** [hazelgrove/hazel#438]
![image](https://user-images.githubusercontent.com/26719164/95791276-06edf400-0caf-11eb-8889-675ffd57f196.png)

When trying to define an annotated tuple variable, when creating the tuple element by element, the cursor gets a "DoesNotElaborate" error when creating a type with a character length of more than 1.

![image](https://user-images.githubusercontent.com/26719164/95791443-60562300-0caf-11eb-8c7d-ffa5b8359f82.png)
In this example, I was trying to create a tuple of value 12, 13.  I was successfully enter 1.  After entering 2, I got this error in the console and was not able to enter any more characters.

**Comment by disconcision** [comment]
Confirming this still exists post pattern-annotations, but throws a new error: 
<img width="1299" alt="Screen Shot 2021-06-27 at 1 00 44 PM" src="https://user-images.githubusercontent.com/22436459/123553200-cd2f2180-d747-11eb-9d6f-dd5ec93bf4f0.png">
(this message means that Statics_Exp.syn(def) returned None)
