### ISSUE TITLE
n>2-tuple patterns not populating sidebar context

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/hazel#441]
<img width="646" alt="Screen Shot 2020-10-20 at 6 35 07 PM" src="https://user-images.githubusercontent.com/22436459/96651734-6bd6c900-1303-11eb-8cee-479c68ff39bc.png">

2-tuples work fine, but for 3+-tuples, we don't get values in the sidebar.

**Comment by cyrus-** [comment]
This is a bug. Might be worth chasing down to help you understand how the dynamics work?

**Comment by cyrus-** [comment]
The intended behavior here is that the pattern matching should succeed. Not sure why it is not succeeding here.
