### ISSUE TITLE
Newline creation from inside operand hole causes invalid instance on subsequent cursor movement.

### ISSUE THREAD

**Issue by claban3** [hazelgrove/hazel#448]
Steps to reproduce:
1. Enter an operator: 
`_ + _`
2. Navigate the cursor to the right side of the left hole:
 `_| + _`
3. Enter a new line:
` _`
`_| + _`
4. Try navigating cursor and no good.

**Comment by cyrus-** [comment]
yeah this bug or something similar to it has been around for a long time @dmoon1221 -- might not be fixed until next big refactor
