### ISSUE TITLE
Binary trees

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#48]
Iterated ML-style constructor applications to build trees for tests and small examples are a real pain point. If you have a particular shape in mind, it can be hard to see if you've actually attained that shape. Much easier would be a palette that let you draw it, tikz style, and interop'ed with the datatype constructors in the described way.

You may also want to have a function like `complete : list A -> tree A` that builds a complete tree with the elements of the argument at the leaves, or `stick : int -> A -> tree A` that makes a linked list of a given length with the repeated argument, or something, as tools that you use in the drawing in the place of nodes to produce whole subtrees that you combine in a particular way. (I've done exactly this for lecture notes any number of times.)

The nice thing is that the kind of gives you a schema for a tree-palette for any W-type, since all inductive types are basically trees with whacky node names if you squint at them the right way.

**Comment by ivoysey** [comment]
from https://github.com/hazelgrove/palettes-paper/issues/2#event-1944571505
