### ISSUE TITLE
remove `is_mac` from model

### ISSUE THREAD

**Issue by dm0n3y** [hazelgrove/hazel#480]
No need to keep `is_mac` in the model. It should just be a global ref set in `Hazel.on_startup`.

**Comment by yottalogical** [comment]
This is something I could work on. Should I open a draft PR and get started?

**Comment by cyrus-** [comment]
@yottalogical you're welcome to do that, but probably better off focusing on something else right now -- this is pretty minor

**Comment by yottalogical** [comment]
Fixed in pull request #523.
