### ISSUE TITLE
type error not shown on body of function

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#481]
![Screenshot from 2021-03-11 15-15-43](https://user-images.githubusercontent.com/280638/110849228-fc934e80-827c-11eb-93af-adf9dc388840.png)

it seems to get fixed if hole fixing runs on it, so something wrong in the action semantics

**Comment by disconcision** [comment]
Should be fixed by https://github.com/hazelgrove/hazel/commit/fc7b59137b0607c0acec9b3fad2a053406993a8d
