### ISSUE TITLE
alt keycombos do not work on mac

### ISSUE THREAD

**Issue by dm0n3y** [hazelgrove/hazel#482]
Dug into this issue with @rntz while trying to set up Alt+H for jumping to hole. Turns out macs change the key value when the alt modifier is held (e.g. Alt+R produces an event with key value "®"). Somehow there does not seem to exist a perfect solution for this. Either we can rely on deprecated keyboard event properties (as suggested in these [StackOverflow](https://stackoverflow.com/questions/52799263/how-to-capture-altn-on-keypress-in-javascript) [posts](https://stackoverflow.com/questions/14109639/how-to-get-alt-cor-any-other-key-to-work-in-javascript-on-chrome-for-mac-and)) or we can use the [`code`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) property to figure out which physical key was pressed, which creates inconsistent behavior for users with non-QWERTY key mappings.

**Comment by cyrus-** [comment]
relying on code is a bit unsatisfying -- what about just detecting "®" when Alt is being pressed and treating it as an Alt+R, and similarly for others?

**Comment by cyrus-** [comment]
do js key handling libraries, e.g. https://github.com/jaywcjlove/hotkeys, handle this somehow?

I'd like to support key rebinding -- as someone who rebinds keys, it's bit me several times when some electron app doesn't do the right thing.

**Comment by yottalogical** [comment]
Fixed in pull request #523.
