### ISSUE TITLE
Elaborated expression decorations are misaligned

### ISSUE THREAD

**Issue by claban3** [hazelgrove/hazel#496]
![image](https://user-images.githubusercontent.com/7157329/114230982-d201e780-9947-11eb-8120-17fb5c60084d.png)

In the above example, it seems like the width of the elaborated holes is shorter than the incremental width added to the inconsistent type operator decoration.

**Comment by cyrus-** [comment]
yeah we need to make DHExp's pretty printing more consistent with UHExp's pretty printing. @coned is working on adding cursors to DHExps for some ideas we are exploring around small stepping, so that might be a context in which to do these cleanups.
