### ISSUE TITLE
Backspacing on an inner let expression (let expression inside another expression)

### ISSUE THREAD

**Issue by kevechen** [hazelgrove/hazel#497]
Currently, backspacing on a inner let expression causes the cursor to freeze and the backspace is unable to be performed. Below are some examples to reproduce the bug: 

Nested let:
![image](https://user-images.githubusercontent.com/33815349/114319011-9567f480-9add-11eb-8202-6ecb04a6670e.png)

Case: 
![image](https://user-images.githubusercontent.com/33815349/114319066-d7913600-9add-11eb-99fd-e91e80541bce.png)

**Comment by disconcision** [comment]
This is redundant to #278; closing
