### ISSUE TITLE
Make move to prev/next hole actions wrap around

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#52]

**Comment by dmoon1221** [comment]
Completed in https://github.com/hazelgrove/hazel/tree/node-staging

**Comment by adamsmd** [comment]
@cyrus- and @dmoon1221: This card is in the "Misc" column of the "Hazel Language" project.  Should it be moved to the "Done" column?

**Comment by cyrus-** [comment]
Yes.

**Comment by adamsmd** [comment]
Done.
