### ISSUE TITLE
Deleting the only one case rule will make hole number growing quickly

### ISSUE THREAD

**Issue by coned** [hazelgrove/hazel#533]
![image](https://user-images.githubusercontent.com/12196892/127884517-133fad9d-b5d3-4410-8314-b443e3a94297.png)

When type Backspace it will not do anything but let the hole number grow. Maybe it first deletes the case rule and program generates a new empty rule because case expression should contain at least one rule.

**Comment by cyrus-** [comment]
Yes, I believe that is the reason for the behavior you're observing. I agree that this is behavior we could tweak to make it less surprising, but low priority at the moment.
