### ISSUE TITLE
Tab to move to next hole bugs with parentheses in patterns, injections in expressions

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/hazel#547]
Not sure if these are the same bug or not:

BUG 1:
move to next hole doesn't seem to work for injections. for example, create a single injection with a hole inside and put the caret anywhere. tab has no effect.

BUG 2 (Hs are holes, C is caret):
pressing tab here:
```
case H
| C(H,H)  => H
end
```
yields
```
case H
| (H,H)  => CH
end
```
instead of 
```
case H
| (CH,H)  => H
end
```
as expected.

I tried briefly to fix these but the issue isn't immediately obvious

**Comment by cyrus-** [comment]
BUG 1 will presumably be fixed by Eric's ADT stuff.

BUG 2 is definitely a bug. The fix should be in the CursorPath code that computes the hole ordering.
