### ISSUE TITLE
Binary operations missing short circuiting behaviour

### ISSUE THREAD

**Issue by braxtonhall** [hazelgrove/hazel#551]
Seen on https://hazel.org/build/dev/

I noticed that operations like `&&` and `||` don't short circuit as one might expect them to.
<img width="258" alt="Screen Shot 2021-10-29 at 10 38 24 AM" src="https://user-images.githubusercontent.com/35436247/139482613-ff12706b-5342-418e-bca6-6a0e450e7b44.png">
I would expect it to evaluate to the same value as this program:
<img width="289" alt="Screen Shot 2021-10-29 at 10 53 15 AM" src="https://user-images.githubusercontent.com/35436247/139483020-18342e27-6e53-4908-ae4e-6fcaf5caec86.png">
I think the problem lies here:
https://github.com/hazelgrove/hazel/blob/c49b60bcc4bf16e752c92c765b42e391294e2aea/src/hazelcore/dynamics/Evaluator.re#L577-L586
`d2` is eagerly evaluated!

I think the easiest solution would be to add a desugar step to translate the surface program into a simpler calculus. The example from the first image might desugar into a program like the one in the second image, although that might result in unintuitive intermediate steps for a user given a stepper.

edit: nope I'm big dumb if you desugar then you'd have to resugar the values at the end if they have holes in them, like `hole || hole`. pls ignore that suggestion

**Comment by cyrus-** [comment]
Thank you for the report! It's been fixed to short circuit properly now.
