### ISSUE TITLE
underscores? in my numbers?

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/hazel#560]
<img width="286" alt="Screen Shot 2021-11-10 at 6 15 07 PM" src="https://user-images.githubusercontent.com/22436459/141208833-c0d0f9a1-3de6-46d4-bef2-fc4f5aa4156b.png">

**Comment by cyrus-** [comment]
Not a bug -- OCaml supports this too, as a way to more clearly write large numbers like `1_000_000`.

**Comment by disconcision** [comment]
Wow, even runs of many underscores I guess. Feels more permissive than I would have expected for a number notation.

**Comment by cyrus-** [comment]
Yeah that's probably unnecessarily permissive but we just defer to OCaml's literal parser iirc.
