### ISSUE TITLE
unreadable text in dark mode

### ISSUE THREAD

**Issue by milahu** [hazelgrove/hazel#563]
hazel renders unreadable text, when the darkreader browser extension is enabled

easy fix: transparent colors for the highlight backgrounds

<img src="https://user-images.githubusercontent.com/12958815/141857833-b3d42726-9458-4dfe-8d01-c8cd00f4343c.png" width="494">

source: https://hazel.org/build/dev/

**Comment by disconcision** [comment]
Hopefully small complication: The closed children here (the pattern holes in the rules, which are white) are actually rendered overtop of the green selection using an explicit color, so cannot be made transparent

**Comment by milahu** [comment]
then we need two colors

per https://github.com/darkreader/darkreader/issues/4494

```html
<html>
  <head>
    <style>
      div.highlight {
        background-color: lightgreen;
      }
      /* darkreader darkmode */
      [data-darkreader-mode="dynamic"] div.highlight {
        background-color: darkgreen;
      }
    </style>
  </head>
  <body>
    <div class="highlight">highlight</div>
    <div>no highlight</div>
  </body>
</html>
```
