### ISSUE TITLE
let with n-tuple destruction not evaluated (n>2)

### ISSUE THREAD

**Issue by AlienKevin** [hazelgrove/hazel#570]
![截圖 2021-12-01 下午6 21 37](https://user-images.githubusercontent.com/22850071/144330082-005df921-2d15-49d7-900f-cc83a0396b3d.png)
Note that `a + b + c` is not evaluated.

**Comment by disconcision** [comment]
See also #441, #515. I believe the core issue here is ~ that DHExps don't support n-tuples, only pairs, so there is an ambiguity in how n-tuples get elaborated/evaluated
