### ISSUE TITLE
let allows binding variable more than once

### ISSUE THREAD

**Issue by jlam55555** [hazelgrove/hazel#573]
See attached image.

![image](https://user-images.githubusercontent.com/8844455/148597317-91f61131-c7e1-4ef2-9d8d-285c3e3bf300.png)

This should probably throw a warning. Also, due to the order of arguments in the way the environment is extended using `Environment.union`, the first binding of the variable is used.

**Comment by mirryi** [comment]
This was also an issue in:

![before](https://user-images.githubusercontent.com/38477923/148662778-aa412268-b3a5-4033-b712-3ba2a6d554ce.png)

I created the branch `fix-branch-case` where an `Environment` of bound variables are passed throughout `matches` to ensure that a variable isn't bound twice in the same pattern to different values. If we try to bind `x` to `5` first and then `6`, `matches` will return `DoesNotMatch`.

This is after:

![after](https://user-images.githubusercontent.com/38477923/148662706-350ecdcc-7243-4739-88dc-6ac7112c139a.png)

Similar to the above example posted by @jlam55555 , the pattern is not matched in a let like this:

![a](https://user-images.githubusercontent.com/38477923/148662950-caa2b41e-e73e-4ed3-b4e3-cb85a0adecf2.png)

However, I used `==` on `DHExp.t` to check if the two values are equal, but I'm not sure if this is correct?

```reason
let rec matches =
        (dp: DHPat.t, d: DHExp.t, bound: Environment.t): match_result =>
  switch (dp, d) {
  ...
  | (Var(x), _) =>
    switch (Environment.lookup(bound, x)) {
    | Some(d') when d == d' => Matches(bound)
    | Some(_) => DoesNotMatch
    | None =>
      let env = Environment.extend(bound, (x, d));
      Matches(env);
    }
  ...
}
```

**Comment by mirryi** [comment]
Alternatively, it could simply be disallowed to use the same variable more than once in the same pattern? In that case, the above `case` example would have to done as:

![example](https://user-images.githubusercontent.com/38477923/148666302-9363daf0-f235-4f2c-bf73-a2bc4827dbf4.png)
