### ISSUE TITLE
Consider tooltip off by default and show keyboard shortcut in help

### ISSUE THREAD

**Issue by AlienKevin** [hazelgrove/hazel#575]
The tooltip is useful for inspecting the types of expressions but can block substantial parts of the next line. I think it might be best if we turn the tooltip off by default. Also, there doesn't seem to be any documented keyboard shortcut in the help section of the web page.

**Comment by cyrus-** [comment]
Agreed. Anyone want to pick this up as a small PR?

**Comment by AlienKevin** [comment]
I can give it a try

**Comment by AlienKevin** [comment]
I made a [cursor-inspector branch](https://github.com/hazelgrove/hazel/tree/cursor-inspector) and turned off cursor inspector by default. However, I can't find a reasonable place to document the keyboard shortcut.
* The left panel contains only edit actions, which cursor inspection is not a part of.
* The top right hamburger bar contains high level layout actions like toggling left/right panels so toggling cursor inspector doesn't quite fit there either.
* The right panel shows context and history related to evaluation so that's also not a good fit.

In addition, pressing ctrl+space or `UpdateCursorInspector(Toggle_visible)` only works when the editor is in focus. Taking all of these into consideration, I can think of four options:
1. We can defer the documentation until condition 3 or 4 is met below.
2. Add a small toggle button at the top left/right corner of the editor with a keyboard shortcut label
3. If there are other non-edit-action shortcuts like these. We can collect them together and show a keyboard shortcuts popup.
4. If we are considering a Preferences section for themes, formatting, etc, we can have a config like "Show cursor inspector by default" there.

**Comment by disconcision** [comment]
right now on the assistant branch i have an icon for this next to the hamburger menu... check it out here: https://hazel.org/build/assistant-1/ . not sure this is a final solution, but any solution should probably take into account that we're going to have a bunch of modes for what is 'docked' to the cursor

**Comment by cyrus-** [comment]
Let's deal with the keyboard shortcut documentation issue together with work on the Assistant, since Andrew has already been thinking about that. For now, you can go ahead and make a PR for the hide-by-default behavior.

**Comment by AlienKevin** [comment]
Made a PR to turn off inspector.
