### ISSUE TITLE
slowdown with long infix expressions (doc generation?)

### ISSUE THREAD

**Issue by jlam55555** [hazelgrove/hazel#587]
Steps for reproduction: open the Hazel editor, press space a few times. Gets very slow very quickly.

![image of reproduction steps](https://user-images.githubusercontent.com/8844455/157381667-a645f11c-a9fe-41f8-af4a-bd0ccfc884c7.png)

It appears to be a problem for ~any infix expression with holes (e.g., also works with holes separated by + signs) and for non-empty holes.~ any long infix expression.

I haven't investigated the cause of this issue, but I might investigate if I have some time. By checking "measure times," it seems to be coming from `Program.get_doc`.

This is not related to https://github.com/hazelgrove/hazel/issues/536 (I'm pretty sure of this; that issue is related to hole instance numbering and holes referencing each other, which doesn't occur in the above example.)

**Comment by disconcision** [comment]
yeah looks to be doc generation. note that this occurs without holes (for example using 1s instead of holes) and when evaluation is turned off

**Comment by jlam55555** [comment]
Thanks for checking, I've edited the issue title
