### ISSUE TITLE
Decorations for tuples/list lits

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#603]

**Comment by disconcision** [comment]
Tuples done except for decorations

**Comment by disconcision** [comment]
@LutSa you could give this a shot as part of the list literals work if you want. The current situation is that, when you're on a comma, it currently just draws the tile decoration for a binary operation, so when you're on a comma, it only draws the backing on that comma, and not the others which make up the list/tuple. Not completely obvious what the best approach for decorations is here, but to a first approximation, we could forget about the lines part of the indicated tile decorations and just drawing the backings on all the comma tiles when you're on any of them. The list literal version should probably back the square brackets as well.

(When you get to this stage, ask David or I for more info.)
