### ISSUE TITLE
Remove extraneous prints to console that have ended up in dev

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#625]

**Comment by xzxzlala** [comment]
I have checked all the "print_endline" function in dev branch, most of them are all informative and good, others (like print a list) are commented. Maybe nothing needs to be removed?

**Comment by cyrus-** [comment]
OK, sounds good -- thanks for checking.

**Comment by disconcision** [comment]
@cyrus- perhaps we should add an alias for print_endline intended for long-lived debug prints

**Comment by cyrus-** [comment]
oh yeah that's a good idea -- I'll add it as a cleanup task
