### ISSUE TITLE
Unhandled Exception "could not find caret" when deleting a whole line in a local binding context

### ISSUE THREAD

**Issue by dedbox** [hazelgrove/hazel#652]
Given the following program and cursor location,

![image](https://user-images.githubusercontent.com/507601/176546599-da9f8547-3e5e-489e-a49b-1f513f6190a3.png)

pressing `Backspace` crashes with the message:

`Async_kernel: Unhandled exception (Failure "could not find caret")`

Expected behavior: the `3` should be replaced with an empty line.

**Comment by disconcision** [comment]
this is #278 i believe

**Comment by dedbox** [comment]
Exactly the same issue I'm seeing.
