### ISSUE TITLE
Crashing on floating-point inequalities

### ISSUE THREAD

**Issue by dedbox** [hazelgrove/hazel#670]
Given the following edit state:

![image](https://user-images.githubusercontent.com/507601/182854833-076bbfab-d8e9-4519-ac61-19a92b5e0752.png)

Expected behavior:

Pressing `.` should replace `<` with its floating point counterpart, producing a basic inequality expression of type `Float`.

Actual behavior:

Pressing `.` crashes the editor and raises `Async_kernel: Unhandled exception  (Failure float_of_string)` in the browser console.

**Comment by disconcision** [comment]
Fixed in #[0536c3d](https://github.com/hazelgrove/hazel/commit/00536c3d5284c18dc701063ea2c0d411a38f11a0)
