### ISSUE TITLE
incorrect free variable error in incomplete let

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#735]
![Screenshot from 2022-08-25 14-41-38](https://user-images.githubusercontent.com/280638/186743665-28421c45-d07f-48ec-b090-539946a1a693.png)

**Comment by disconcision** [comment]
This is because the x is being parsed (by maketerm) as an expression; so this is downstream of a better term generation strategy for incomplete tiles (i'm still not super clear on what our plan is/should be here)
