### ISSUE TITLE
strange results when backpack is non-empty

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#754]
this is in the 490F22-discussion1 branch:

![Screenshot from 2022-09-02 01-10-56](https://user-images.githubusercontent.com/280638/188063526-fd44ce01-1f49-4bba-83a8-85a0517263d3.png)

not sure why the result is being displayed as `4`

**Comment by dm0n3y** [comment]
no guarantees about incomplete semantic behavior before nary-skels (which happens to includes changes to term parsing and statics to handle incompleteness)
