### ISSUE TITLE
DHExp components overlap with spaces

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#755]
a, b, c, d all overlap in the output at some offset from one another (easier to see as you type it in). not sure what's going on here.

![Screenshot from 2022-09-02 01-15-39](https://user-images.githubusercontent.com/280638/188063914-2d9a2417-304b-403c-8087-c664b2e3e2c4.png)

**Comment by disconcision** [comment]
multihole (what concave hole sequences get expanded to) are being expanded to DHExp.sequences (somewhat arbitrary decision on my part; they should be their own thing at some point, but that needs evaluator logic (+dhdoc...), which was waiting on the hazel2 evaluator work ). these are displayed vertically, as in hazel2 sequence == lines. and i'm limiteing dhexp displays to a single line, which i guess is causing this
