### ISSUE TITLE
comma binds more tightly than fun

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#757]
![image](https://user-images.githubusercontent.com/280638/188170509-b1f2b772-5074-432e-8219-3cdd2bcb9b23.png)

**Comment by dm0n3y** [comment]
this is based on ocaml's operator precedence but I guess with tight ap we don't want this? should comma be lowest?

**Comment by cyrus-** [comment]
Yeah I think so, or else we need a right delimiter for fun...

**Comment by disconcision** [comment]
I think tuples should require parens

**Comment by cyrus-** [comment]
you want function application to be `f((a, b, c))`?

**Comment by disconcision** [comment]
no, but i'm fine with special-casing application

**Comment by disconcision** [comment]
or another a way of looking at it maybe: disambiguation parens aren't a thing. parens with no contained commas always creates a one-tuple. one-tuples have identical semantics to the contained term. function application syntactically requires a tuple for the argument.

**Comment by cyrus-** [comment]
We can discuss but regardless, it wouldn't solve the problem in this issue so lets make a separate thread about that?
