### ISSUE TITLE
long code decorations go out of sync with code

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#763]
![image](https://user-images.githubusercontent.com/280638/188802834-e34f2b23-3b06-4204-9069-4ab26d7d95f8.png)

**Comment by cyrus-** [comment]
I believe this has been fixed.

**Comment by disconcision** [comment]
it has been mitigated, likely adequately so. the origin iirc is a chrome rounding bug which we worked around. currently on chrome a token of ~1200 characters long will have a decoration ~1 character short. this does not occur on firefox. the discrepancy does not become noticeable unless you have a token around ~8 times screenwidth at 100% zoom, so closing seems reasonable.
