### ISSUE TITLE
Pattern guards

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#77]
The Successor ML version of them is quite nice because the guard is part of the syntax of patterns (compared to the OCaml one and others where it is part of the syntax of rules).

John Reppy had a short paper at the ML workshop 2019 for reference.

**Comment by brendanzab** [comment]
You wouldn't happen to know of links to more information about these?

**Comment by brendanzab** [comment]
Ahh, here's John Reppy's paper: [Compiling Successor ML Pattern Guards](http://people.cs.uchicago.edu/~jhr/papers/2019/ml-guards.pdf)
