### ISSUE TITLE
Builtin Functions

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#780]

**Comment by mirryi** [comment]
For parity with dev this is just a matter of changing the initial type context for statics and wrapping elaborated dhexps in let bindings with the builtins (copy over a few dev changes).

For per-exercise builtins, we could add properties to the exercise specs that provide the builtins (an initial context and a map of dhexp forms) for that exercise? Then we simply pass the initial context to `Statics.mk_map` and the dhexp forms to `Elaborator.uexp.elab`.

**Comment by cyrus-** [comment]
Sounds reasonable. Do you have time to do this over the next few days?

**Comment by mirryi** [comment]
Yeah I think I should.
