### ISSUE TITLE
fix DHExp printing to be consistent with surface syntax

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#782]
examples of inconsistencies:
- ap uses space instead of parens
- ...

**Comment by YC-Qiu** [comment]
Could you give more details about this issue? I’m not sure what ap is.

**Comment by cyrus-** [comment]
@YC-Qiu ap is function application. currently the Hazel surface syntax uses parentheses: `f(x)` but the internal language printer uses space `f x`

**Comment by YC-Qiu** [comment]
OK. It seems a simple issue. I'm working on it now.
