### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#831]

**Comment by linsyking** [comment]
Should we allow user to use `undefined` variables?

For example, is this valid?

```
let a = undefined in
```

**Comment by cyrus-** [comment]
yes that is fine

**Comment by linsyking** [comment]
Figured out why it will crash.

It complains that `form_group` doesn't have `undefined_exp_group`.

In `Store.re`, https://github.com/hazelgrove/hazel/blob/dev/src/haz3lweb/Store.re#L89

The lang doc uses localstore data. So I clean the cache and it doesn't crash anymore.

**Comment by linsyking** [comment]
![image](https://github.com/hazelgrove/hazel/assets/49303317/3621d994-2251-4f2a-8fe6-02c75c4a86a2)
This works now, but not sure what this mean:

> The one difference between an empty hole and undefined is that undefined should not be a valid pattern in a case expression. I'm still working on making that behavior work properly.

Do we have any examples?

**Comment by cyrus-** [comment]
- Undefined should not be capitalized in the output
- I believe that comment is saying that you should not be able to bind a variable called "undefined" in patterns.

**Comment by linsyking** [comment]
> * Undefined should not be capitalized in the output
> * I believe that comment is saying that you should not be able to bind a variable called "undefined" in patterns.

![image](https://github.com/hazelgrove/hazel/assets/49303317/bf6ccc91-935c-420c-8fe6-aa78110988f5)
Is this correct?

**Comment by cyrus-** [comment]
That looks right, yes!
