### ISSUE TITLE
Make it possible to navigate through a DHExp with cursor

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#856]
Possibly best way to do this is to translate DHExp to UExp, which will require adding a few forms to UExp (e.g. how to handle fix) and/or coming up with a secondary data structure that associates things like casts and run-time errors.

**Comment by disconcision** [comment]
perhaps (though not necessarily) a point in favor of combining dhexp and uexp. we should make a list of the issues that touch these data structures, as there are a few of them now, in order to decide on a strategic approach to avoid redundant functionality
