### ISSUE TITLE
Replace old dynamics types with new ones from haz3l

### ISSUE THREAD

**Issue by mirryi** [hazelgrove/hazel#859]
Replace in dynamics:

- `Var.t` -> `Token.t`
- `VarCtx.t` -> `Ctx.t`?
- `HTyp.t` -> `Typ.t`?
- ...

**Comment by disconcision** [comment]
FYI I've already eliminated HTyp in my casting branch. but for sure yeah the others should be done, and there's more as well... like even if we don't merge dhexp and uexp, all of the helper types like the binop stuff could probably be merged
