### ISSUE TITLE
Proposal: DHExp/UExp merge

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/hazel#878]
This intended to be a running discussion on the benefits/drawback of eliminating DHExp. Will be adding things as I think of them.

PROS:

- One less data type (they are already very similar)
- Opportunity to clear/clean up quirks/redundancies in DHExp.t
- Unique ids in evaluation; useful for tracking dynamic data for things like e.g. perf heatmaps
- View layer consolidation without backwards conversion

CONS:

- conceptual: What does it mean to elaborate a cast?
- still need a separate notion of typing maybe? given unicity?

**Comment by mirryi** [comment]
Further cons:

- Departure from papers in a pretty drastic way; harder to reason about in general (imo), especially for new folks
- With environments, there are already quite a lot of invariants to keep track of for DHExp that the type system can't help you much with

**Comment by cyrus-** [comment]
This recent paper shows how to implement gradual typechecking directly on the source language: https://i.cs.hku.hk/~bruno/papers/ecoop2021.pdf. Worth exploring imo!

**Comment by mirryi** [comment]
Was there a decision made about this? #931 seems to be doing this?

**Comment by cyrus-** [comment]
We're exploring it yeah, let's see what the challenges are. In terms of thinking about the code I think there is de facto still a UExp/DHExp distinction with the attending invariants, but having them use the same implementation type underneath is good. In fact, we should probably have UExp and DHExp both remain in the code as documentation.

**Comment by mirryi** [comment]
What exactly are the advantages using the same implementation type underneath? It just seems like we'd be shifting some big responsibilities that were previously with the typechecker to the programmer. And if I see a `UHExp.t` or a `DHExp.t` I know immediately what it is; if I just see `HExp.t` (or whatever it ends up being called), I won't.

None of the pros above strike out to me as very big ones:

> PROS:
> - One less data type (they are already very similar)

They're similiar in some ways, but different in drastic ways that I think far outweight the similiarities: casting, closures, fixpoints

> - Opportunity to clear/clean up quirks/redundancies in DHExp.t

I agree there are things about `DHExp.t` we should clean up, but those can be done without a merger

> - Unique ids in evaluation; useful for tracking dynamic data for things like e.g. perf heatmaps

I don't see why we couldn't add unique ids without a merger

> - View layer consolidation without backwards 

What exactly is meant by view layer consolidation? What features do we need for the rendering of `DHExp.t`? 

Other thoughts that I think discourage this:

- Other tools that don't use the Hazel web UI (e.g. the compiler) that aren't concerned with UI things would fare better with a clear, standalone `DHExp.t` type
- In general it feels like we should be moving towards more explicit API boundaries---I'm in favor of separating the statics and dynamics into separate libraries, but this feels a bit like the opposite
