### ISSUE TITLE
Dynamic type not working

### ISSUE THREAD

**Issue by AlienKevin** [hazelgrove/hazel#895]
Example: Define a variable `x` with a hole type. At runtime, `x` is evaluated to `1` which has type `Int`.

<img width="446" alt="Screen Shot 2022-10-04 at 11 23 56 AM" src="https://user-images.githubusercontent.com/22850071/193860300-d236da41-8d90-496a-a2e2-1daf77f0d874.png">

`x + 2` fails even though it should produce `3`

<img width="444" alt="Screen Shot 2022-10-04 at 11 22 22 AM" src="https://user-images.githubusercontent.com/22850071/193860127-777b399a-0450-4f4b-aa9d-dc50830cee34.png">

Annotating `x` with `Int` allows plus to work.

<img width="442" alt="Screen Shot 2022-10-04 at 11 22 08 AM" src="https://user-images.githubusercontent.com/22850071/193860133-e953496c-fbfe-446d-8a94-594deee0c3c6.png">

**Comment by disconcision** [comment]
yup casting is currently borked. working on it. until then having persistent holes in type annotations should be avoided
