### ISSUE TITLE
Small-step Evaluator cannot Evaluate Case Expressions

### ISSUE THREAD

**Issue by DavidFangWJ** [hazelgrove/hazel#949]
In the small-step evaluator, case expression will not be properly evaluated. It seems that it is treated as an atomic expression and will not change. In Scratch 1 `StepDoesNotMatch` error is reported, and in Scratch 2 there is no error report, but the evaluator cannot proceed once it expands the if statement into a case expression.

**Comment by tonyfettes** [comment]
The pull request #902.

Transcript of Scratch 2
```
let factorial : Int -> Int = fun x ->
  if x == 0 then 1
  else x * factorial(x - 1)
in
let double_recursively : Int -> Int =
  fun n ->
    if n == 0 then 0
    else dobule_recursively(n - 1) + 2
in

factorial(5)
```

Some initial thoughts.
1. The `StepDoesNotMatch` is raised in `EvalObj.unwrap`, and currently we don't have `ConsistentCase` and `InconsisentBranches` implemented.
2. The small-step evaluator unable to decompose and evaluate fix point for now, so it can't do recursive function call for now.

**Comment by tonyfettes** [comment]
Solved in commit https://github.com/hazelgrove/hazel/pull/902/commits/69b65d1bbbb3375548dd129854d1e60975e63fd1
