### ISSUE TITLE
Unable to substitution with the result of a case expression, which led to shutdown of the entire website

### ISSUE THREAD

**Issue by DavidFangWJ** [hazelgrove/hazel#977]
When I tries to substitute something into a case expression (or something that will evaluate into a case expression) in the small-step evaluator, exception will be thrown, and nothing else will function on the webpage before the next refresh.

I have tried two following examples, both of which will induce the bug.

```
let (a, b) = (1, 2) in
let x =
  let y =
    if a > b then 1 else 0
in 0
```

```
let (a, b) = (1, 2) in
let x =
  let y =
    if 1 < 0 then a else b
in 0
```

**Comment by tonyfettes** [comment]
Both of your example correctly evaluates to hole in the small step evaluator.

I've tested the evaluation of case, using
```
let (a, b) = (1, 2) in
let x =
  let y =
    if a > b then 1 else 0
  in 0
in 0
```
It also gives the correct answer, no expcetion is thrown.

Here is a screenshot of the execution trace:
![image](https://user-images.githubusercontent.com/29998228/218011474-a032138e-565c-4394-b8e9-5bf7ac74b9dd.png)

**Comment by tonyfettes** [comment]
Confirm solved.
