### ISSUE TITLE
feature request: submenus

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/hazel#984]
just noticed we have the same icon representing three different actions. a new submenu widget would be nice for these; heres a quick mockup:

<img width="652" alt="Screen Shot 2023-02-09 at 4 13 23 PM" src="https://user-images.githubusercontent.com/22436459/217943089-bcd70f7d-fff4-4399-82c7-9e5182cb61a3.png">

**Comment by tonyfettes** [comment]
Can I know how you mock up the menu? It looks pretty, and I want to use it for displaying the evluation options (in haz3lweb/view/dhcode/Settings.re). Thank you in advance!

**Comment by disconcision** [comment]
@tonyfettes i used photoshop, which i can do very fast, but unfortunately does not help accelerate the process of actually implementing it. however if someone is interested in implementing the functionality of such a submenu though, disregarding appearance, i'm happy to do the css, as it i can do it very quickly if all divs are tagged with reasonable class names

**Comment by tonyfettes** [comment]
@disconcision I tried, but for now the best I got is something looks like this:
![image](https://user-images.githubusercontent.com/29998228/217978393-10970475-bed7-41ee-b0e3-4ed4bd04792c.png)

I don't know how to place the box on the right side of the toolbar, other than hardcode the distance... Currentlly I put the list and the icon under a div called submenu. Is this ideal?

**Comment by disconcision** [comment]
right now the icons are just 'loose' in the top-level menu. it looks like you're absolutely positioning the submenu with respect to the icon, which means you won't be able to get it to align to the side of the menu itself.

so id suggest adding square container divs inside the top-level menu div which fill the full width of the menu. the icons divs can be centered inside the squares, and the submenu divs can be inside the containers, but absolutely positioned so as to align with the top and right of the squares and hence the side of the menu. the height of submenu items should be the same as the height/width of the squares

**Comment by disconcision** [comment]
yeah err regardless actually you may have to hardcode the distance unless you add some more divs... i think its fine to hardcode here
