### ISSUE TITLE
Optimize logging and state saving

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/hazel#988]
Relatively easy gains to be had here.

Make writes to localstore async so that they don't block the UI. The expensive functions are Update.save_editors and Log.append_entry. The latter is only expensive when the log is large. It probably should also be refactored to no longer depend on log length, but the async change would successfully sweep that under the carpet I think.

**Comment by cyrus-** [comment]
Related: we should probably switch to using IndexedDB from a Web Worker rather than local storage. fixes the log length issue. local storage cannot be accessed from a worker.

**Comment by disconcision** [comment]
perfmageddon closes the saving issue. for logging easiest is probably just switch to using individual kvs per entry, either still with localstorage or with indexedDB. need to decide when to move them back into memory though... just when exporting?

**Comment by cyrus-** [comment]
You mean something like having an incrementing index and then collecting them on export? I think that should work?
